// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// LoginRequest represents a login request
type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// LoginResponse represents a login response
type LoginResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *LoginResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *LoginResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// Health check messages
type HealthRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthRequest) Reset()         { *m = HealthRequest{} }
func (m *HealthRequest) String() string { return proto.CompactTextString(m) }
func (*HealthRequest) ProtoMessage()    {}
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *HealthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthRequest.Unmarshal(m, b)
}
func (m *HealthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthRequest.Marshal(b, m, deterministic)
}
func (m *HealthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthRequest.Merge(m, src)
}
func (m *HealthRequest) XXX_Size() int {
	return xxx_messageInfo_HealthRequest.Size(m)
}
func (m *HealthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthRequest proto.InternalMessageInfo

type HealthResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Service              string   `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthResponse) Reset()         { *m = HealthResponse{} }
func (m *HealthResponse) String() string { return proto.CompactTextString(m) }
func (*HealthResponse) ProtoMessage()    {}
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *HealthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthResponse.Unmarshal(m, b)
}
func (m *HealthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthResponse.Marshal(b, m, deterministic)
}
func (m *HealthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthResponse.Merge(m, src)
}
func (m *HealthResponse) XXX_Size() int {
	return xxx_messageInfo_HealthResponse.Size(m)
}
func (m *HealthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthResponse proto.InternalMessageInfo

func (m *HealthResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *HealthResponse) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *HealthResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "auth.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "auth.LoginResponse")
	proto.RegisterType((*HealthRequest)(nil), "auth.HealthRequest")
	proto.RegisterType((*HealthResponse)(nil), "auth.HealthResponse")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0x51, 0x4b, 0xf3, 0x30,
	0x14, 0x86, 0xd9, 0xf7, 0x6d, 0xdd, 0x3c, 0x3a, 0x85, 0x38, 0xb4, 0xec, 0x4a, 0x7a, 0xe5, 0xcd,
	0x56, 0x71, 0xf8, 0x03, 0xf4, 0x42, 0x14, 0xbc, 0x9a, 0x77, 0x22, 0x48, 0x96, 0x1d, 0xda, 0xe0,
	0x9a, 0xc4, 0x9c, 0x64, 0xe2, 0xbf, 0x97, 0xa4, 0xe9, 0xb0, 0x77, 0x7d, 0xde, 0xb7, 0x3d, 0x7d,
	0x72, 0x02, 0xc0, 0xbd, 0xab, 0x97, 0xc6, 0x6a, 0xa7, 0xd9, 0x30, 0x3c, 0x17, 0x8f, 0x70, 0xf2,
	0xa2, 0x2b, 0xa9, 0xd6, 0xf8, 0xe5, 0x91, 0x1c, 0x9b, 0xc3, 0xc4, 0x13, 0x5a, 0xc5, 0x1b, 0xcc,
	0x07, 0x57, 0x83, 0xeb, 0xa3, 0xf5, 0x81, 0x43, 0x67, 0x38, 0xd1, 0xb7, 0xb6, 0xdb, 0xfc, 0x5f,
	0xdb, 0x75, 0x5c, 0x58, 0x98, 0xa6, 0x39, 0x64, 0xb4, 0x22, 0x64, 0x39, 0x8c, 0xc9, 0x0b, 0x81,
	0x44, 0x71, 0xce, 0x64, 0xdd, 0x61, 0x68, 0x1a, 0x24, 0xe2, 0x15, 0xa6, 0x29, 0x1d, 0xb2, 0x4b,
	0x18, 0x87, 0x9f, 0x7d, 0xc8, 0x6d, 0xfe, 0x3f, 0x36, 0x59, 0xc0, 0xe7, 0x2d, 0x9b, 0xc1, 0xc8,
	0xe9, 0x4f, 0x54, 0xf9, 0x30, 0xc6, 0x2d, 0x14, 0x67, 0x30, 0x7d, 0x42, 0xbe, 0x73, 0x75, 0x92,
	0x2f, 0xde, 0xe1, 0xb4, 0x0b, 0x92, 0xc5, 0x05, 0x64, 0xe4, 0xb8, 0xf3, 0x94, 0x0e, 0x93, 0x28,
	0xda, 0xa1, 0xdd, 0x4b, 0x71, 0x70, 0x48, 0x18, 0x9a, 0x3d, 0x5a, 0x92, 0x5a, 0x25, 0x87, 0x0e,
	0x6f, 0x1d, 0x1c, 0xdf, 0x7b, 0x57, 0xbf, 0xa6, 0x17, 0x6f, 0x60, 0x14, 0x4f, 0xcc, 0xd8, 0x32,
	0x6e, 0xf5, 0xef, 0x1a, 0xe7, 0xe7, 0xbd, 0x2c, 0xc9, 0xac, 0x20, 0x6b, 0xf5, 0x58, 0xaa, 0x7b,
	0xf6, 0xf3, 0x59, 0x3f, 0x6c, 0x3f, 0x7a, 0xb8, 0x7b, 0x5b, 0x55, 0xd2, 0xd5, 0x7e, 0xb3, 0x14,
	0xba, 0x29, 0x8d, 0xfc, 0xf1, 0xba, 0xac, 0xf4, 0x42, 0x68, 0xaf, 0x1c, 0xda, 0x05, 0xf1, 0xc6,
	0xec, 0xb0, 0x94, 0x01, 0x14, 0xdf, 0x95, 0x95, 0x35, 0xa2, 0x34, 0x9b, 0x4d, 0x16, 0x2f, 0x79,
	0xf5, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x0c, 0x78, 0xd5, 0xe5, 0xf2, 0x01, 0x00, 0x00,
}
